name:                haskell-two
version:             0.1.0.0
github:              "githubuser/haskell-two"
license:             BSD3
author:              "Daniel Hao Huynh"
maintainer:          "daniehhu@stud.ntnu.no"
copyright:           "2022 Daniel Hao Huynh"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-two#readme>

dependencies:
- base >= 4.7 && < 5
- random 
- time

library:
  source-dirs: 
    - "src"

executables:
  hello-name-exe:
    main:                Hello-Name.hs
    source-dirs:         helloname
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-two

  word-count-exe:
    main:                Word-Count.hs
    source-dirs:         wordcount
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-two

  guess-number-exe:
    main:                Guess-Number.hs
    source-dirs:         guessnumber
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-two

  pairs-d-exe:
    main:                Pairs-D.hs
    source-dirs:         pairsd
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-two

  count-birds-exe:
    main:                Count-Birds.hs
    source-dirs:         countbirds
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-two

tests:
  haskell-two-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-two
    - doctest
    - QuickCheck
    - HUnit
    - hspec